# Copy to secrets.yaml and fill in your values
wifi_ssid: "YOUR_WIFI_SSID"
wifi_password: "YOUR_WIFI_PASSWORD"
api_key: "YOUR_ESPHome_API_ENCRYPTION_KEY"
ota_pwd: "YOUR_ESPHome_OTA_ENCRYPTION_KEY"
ap_pwd: "YOUR_ESPHome_AP_ENCRYPTION_KEY"
mac_01: "AA:BB:CC:DD:EE:FA"
mac_02: "AA:BB:CC:DD:EE:FB"
